visible:
  - stripe
  - coreos
  - apple
  - friendlyu
  - busyconf
items:
  -
    key: stripe
    company: Stripe
    title: Software Engineering Intern
    website: stripe.com
    timeline: Summer 2017
    bullets:
      - Developed system for constructing complex PDFs
      # - Worked with design team through PDF iterations
      - Maintained configuration of production services
      - Coordinated requirements between teams
      - Integrated observability metrics into key features
  -
    key: coreos
    company: CoreOS
    title: Software Engineering Intern
    website: coreos.com
    timeline: Fall 2016
    bullets:
      - Built graphing components to surface Kubernetes metrics
      - Built UI for control of updates to Kubernetes clusters
      - Migrated various web components from Angular to React
  -
    key: apple
    company: Apple
    title: Software Engineering Intern
    website: apple.com
    timeline: Summer 2016
    bullets:
      - Developed custom content editor & platform
      - Implemented instructional content for product tours
      - Created deployment workflow to be used across projects
  -
    key: datto
    company: Datto
    title: Software Engineering Intern
    website: datto.com
    timeline: Summer 2015
    bullets:
      - Developed interactive API query builder
      - Designed API home and documentation pages
      - Built automated system for packaging the API
      - Developed documentation system for API
  -
    key: friendlyu
    company: FriendlyU
    title: Software Engineer
    website: friendlyu.com
    timeline: Summer 2015 - Present
    bullets:
      - Built cross-website widget for chat feature
      - Implemented UI and motion flows
      - Integrated JavaScript build systems using Webpack
      - Optimized code for installation in third-party websites
  -
    key: oliveraweb
    company: Olivera Web
    title: Founder, Freelancer
    website: oliveraweb.com
    timeline: 2009 - Present
    bullets:
      - Developed custom web apps for scheduling, teaching
      - Designed unique personal &amp; business websites
      - Created &amp; maintain Linux hosting services
  -
    key: busyconf
    company: BusyConf
    title: Software Intern
    website: busyconf.com
    url: http://busyconf.com
    timeline: 2013 - 2015
    bullets:
      - Improved design & clarity of front-end interfaces
      - Maintained various pieces of a Ruby on Rails app
      - Migrated billing provider to Stripe
      - Integrated third party APIs
