visible:
  - nntpbridge
  - cshdrink
  - brickhack
items:
  -
    key: nntpbridge
    name: Discourse NNTP Bridge
    title: Personal Project
    website: github.com/sman591/discourse-nntp-bridge
    timeline: Winter 2016 - Present
    bullets:
      - Plugin to sync NNTP posts with a Discourse forum
      - Asynchronous execution for reliability, retries
      - Integrated automated testing with Travis CI
      - Utilized Ruby on Rails Engine functionality
  -
    key: cshdrink
    name: CSH Drink for iOS
    title: Personal Project
    website: github.com/sman591/csh-drink-ios
    timeline: Winter 2015 - Present
    bullets:
      - Developed app to access CSH vending machines
      - Designed consistent UI with other CSH iOS apps
      - Integrated seamless login via URL schemes
      - Integrated REST API
  -
    key: brickhack
    name: BrickHack.io
    title: Collaborative Project
    website: brickhack.io
    timeline: Fall 2014 - Present
    bullets:
      - Developed registration, management interface
      - Created live statistics dashboard to track progress
      - Managed code contributions
      - Configured continuous integration systems
  -
    key: pegg
    name: iOS App Challenge - Pegg
    title: Team Hackathon
    website: devpost.com/software/pegg
    timeline: Winter 2015
    bullets:
      - Implemented community and social capabilities
      - Developed photo-taking app
      - Connected with custom API
  -
    key: datamine
    name: DataMine
    title: Collaborative Project
    website: datamine.oweb.co
    timeline: Winter - Spring 2013
    bullets:
      - Developed front-end driven website (Backbone.js)
      - Developed backend REST API (PHP)
      - Community data share platform
  -
    key: ritassassins
    name: RIT Assassins
    title: Collaborative Project
    website: rit-assassins.github.io/arit-www/
    timeline: Summer 2014
    bullets:
      - Developed front-end driven website (AngularJS)
      - Integrated REST API
      - Integrated Facebook authentication
